HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-5-x86_64 
    hypervisor: vcloud
    template: centos-5-x86_64
  agent:
    roles:
      - agent
    platform: el-5-i386
    hypervisor: vcloud
    template: centos-5-i386 
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
