HOSTS:
  master:
    roles:
      - master
      - agent
    platform: ubuntu-10.04-x86_64
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/ubuntu-1004-x86_64
  agent:
    roles:
      - agent
    platform: ubuntu-10.04-i386
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/ubuntu-1004-i386
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
