HOSTS:
  master:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
  rhel-agent:
    roles:
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-i386
  fedora-agent:
    roles:
      - agent
    platform: fedora-20-i386
    hypervisor: vcloud
    template: fedora-20-i386
  ubuntu-agent:
    roles:
      - agent
    platform: ubuntu-precise-i386
    hypervisor: vcloud
    template: ubuntu-1204-i386
  wheezy-agent:
    roles:
      - agent
    platform: debian-wheezy-i386
    hypervisor: vcloud
    template: debian-7-i386
  centos-agent:
    roles:
      - agent
    platform: centos-6-i386
    hypervisor: vcloud
    template: centos-6-i386
  solaris-agent:
    roles:
      - agent
    platform: solaris-11-x86_64
    hypervisor: vcloud
    template: solaris-11-x86_64
  win2003r2-ruby193-2:
    roles:
      - agent
    platform: windows-2003r2-32
    ruby_arch: x86
    hypervisor: vcloud
    template: win-2003r2-i386
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
